### ISSUE TITLE
Highlight icon if timer is running

### ISSUE THREAD

**Issue by ocean90** [wearerequired/harvest-chrome#5]
Something like this:

```css
.harvest-timer.running .icon-clock-sm {
    color: #3197d6;
    display: inline-block;
    animation: rotate 4s linear infinite;
}

@keyframes rotate {
    100% {
        transform: rotate(360deg);
    }
}
```
